HEME_S0_ZSCORE     ?= -3
CAVITY_MD_ZSCORE   ?= 5
HEME_T2S_ZSCORE    ?= -2
CAVITY_T2S_ZSCORE  ?= 3

MGE_CROP          ?= 5:-5,:,5:-5
MT_CROP           ?= 10:-10,:,5:50
DWI_NLM           ?= 0.075
MGE_NLM           ?= 0.125
MT_NLM            ?= 0.075
